CREATE TABLE IF NOT EXISTS device_state (
  id INT NOT NULL PRIMARY KEY,
  led_r TINYINT UNSIGNED NOT NULL DEFAULT 0,
  led_g TINYINT UNSIGNED NOT NULL DEFAULT 0,
  led_b TINYINT UNSIGNED NOT NULL DEFAULT 0,

  last_beep_ms INT NOT NULL DEFAULT 0,
  last_beep_duty INT NOT NULL DEFAULT 0,

  song_is_playing TINYINT(1) NOT NULL DEFAULT 0,
  song_gap_ms INT NOT NULL DEFAULT 20,
  song_duty INT NOT NULL DEFAULT 110,
  song_json MEDIUMTEXT NULL,

  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO device_state (id) VALUES (1);

CREATE TABLE IF NOT EXISTS request_log (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip VARCHAR(45) NOT NULL,
  method VARCHAR(8) NOT NULL,
  endpoint VARCHAR(64) NOT NULL,
  query_string VARCHAR(512) NOT NULL,
  user_agent VARCHAR(255) NOT NULL,
  body_trunc TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_request_log_ts ON request_log(ts);
CREATE INDEX idx_request_log_ip ON request_log(ip);
CREATE INDEX idx_request_log_endpoint ON request_log(endpoint);